Repository Kusitms-28th-Kukerton-E/Frontend, pull requests merged in 2023-10, with the labels that each got.

#3 design: add button component
  package.json
  src/components/button.tsx
  src/layout/header.tsx
  src/layout/layout.tsx
  src/style/color.css
  src/style/global.tsx
  yarn.lock
Labels: 🎨 Design, 😈chaemin

#7 Feature/#1/login
  src/api/index.ts
  src/assets/register/register_body.png
  src/assets/register/register_header.png
  src/components/button.tsx
  src/page/Login/index.tsx
  src/page/Register/index.tsx
  src/router/router.tsx
  src/style/common.tsx
  src/style/global.tsx
  src/types/index.ts
Labels: ✨Feature, 🐣minha

#12 Feature/#5/main volunteer
  package.json
  src/layout/header.tsx
  src/page/Home/VolunteerPage.tsx
  src/page/Home/category.tsx
  src/page/Home/index.tsx
  src/page/Home/teacher.tsx
  src/router/router.tsx
  yarn.lock
Labels: ✨Feature, 😈chaemin, 🔨fix

#16 feat: add some components in mypage
  src/page/Home/VolunteerPage.tsx
  src/page/mypage/index.tsx
  src/page/mypage/myInfo.tsx
  src/page/mypage/review.tsx
  src/page/mypage/subTitle.tsx
  src/page/mypage/temperature.tsx
  src/router/router.tsx
  src/types/index.ts
Labels: ⚙ Chore, ✨Feature, 😈chaemin, 🔨fix

#21 Feature/mypage
  src/page/mypage/KidMyPage.tsx
  src/page/mypage/OrgaHistory.tsx
  src/page/mypage/OrgaMyInfo.tsx
  src/page/mypage/OrganizationMyPage.tsx
  src/page/mypage/VolunteerMyPage.tsx
  src/page/mypage/child/childHistory.tsx
  src/page/mypage/childReview.tsx
  src/router/router.tsx
  src/types/index.ts
Labels: ⚙ Chore, ✨Feature, 😈chaemin, 🔨fix
